# Generated by Django 6.1 on 2026-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('sci-fi', 'Фантастика'), ('business', 'Бизнес и саморазвитие'), ('detective', 'Детективы'), ('children', 'Детские книги')], default='fiction', max_length=50, verbose_name='Жанр')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Обложка книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
